### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/documenting-your-code#13]
URL: /en/projects/documenting-your-code

"Support others in the design and build of their digital making projects" This link returns an empty page.

**Comment by martinohanlon** [comment]
It is in step 1

![image](https://user-images.githubusercontent.com/2329501/100605940-9a7f9080-3300-11eb-83e6-0852742b12e2.png)

It should link to this URL - https://curriculum.raspberrypi.org/programming/developer/

**Comment by libxx1** [comment]
Thanks @martinohanlon , fixed now.
